
name: publish
on:
  push:
    branches: [ release ]
jobs:
  pack:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100
    - name: Pack
      run: dotnet pack -warnaserror -c Release
    - name: Publish package
      run: dotnet nuget push -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json artifacts/pack/serde-dn.*.nupkg